// =====================================================================
// QUANTPULSE — Master Stock Universe & Metadata Registry
// Contains complete information on all stocks (Short Name, Full Name,
// Segment, Exchange, Sector, Dhan Security ID, Lot Size, Strike Step,
// and 20-Day Baseline Volume).
// =====================================================================

import { StockMasterItem, Stock } from '../types/quant';

export const STOCK_MASTER_CATALOG: StockMasterItem[] = [
  {
    ticker: 'RELIANCE',
    name: 'Reliance Industries Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Oil & Gas / Conglomerate',
    securityId: '1330',
    lotSize: 250,
    strikeStep: 50,
    avgVol20DM: 5.20,
    approxLtp: 2968.50,
    isFnO: true,
  },
  {
    ticker: 'TCS',
    name: 'Tata Consultancy Services Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Information Technology',
    securityId: '11536',
    lotSize: 175,
    strikeStep: 50,
    avgVol20DM: 1.50,
    approxLtp: 4126.00,
    isFnO: true,
  },
  {
    ticker: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Private Banking & Financials',
    securityId: '1333',
    lotSize: 550,
    strikeStep: 20,
    avgVol20DM: 6.00,
    approxLtp: 1644.20,
    isFnO: true,
  },
  {
    ticker: 'ICICIBANK',
    name: 'ICICI Bank Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Private Banking & Financials',
    securityId: '4963',
    lotSize: 700,
    strikeStep: 20,
    avgVol20DM: 7.00,
    approxLtp: 1258.00,
    isFnO: true,
  },
  {
    ticker: 'INFY',
    name: 'Infosys Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Information Technology',
    securityId: '1594',
    lotSize: 400,
    strikeStep: 20,
    avgVol20DM: 6.80,
    approxLtp: 1890.00,
    isFnO: true,
  },
  {
    ticker: 'SBIN',
    name: 'State Bank of India',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Public Sector Banking',
    securityId: '3045',
    lotSize: 750,
    strikeStep: 10,
    avgVol20DM: 14.50,
    approxLtp: 785.00,
    isFnO: true,
  },
  {
    ticker: 'BHARTIARTL',
    name: 'Bharti Airtel Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Telecommunications',
    securityId: '10604',
    lotSize: 475,
    strikeStep: 20,
    avgVol20DM: 6.20,
    approxLtp: 1540.00,
    isFnO: true,
  },
  {
    ticker: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Private Banking',
    securityId: '1922',
    lotSize: 400,
    strikeStep: 20,
    avgVol20DM: 4.80,
    approxLtp: 1820.00,
    isFnO: true,
  },
  {
    ticker: 'LT',
    name: 'Larsen & Toubro Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Infrastructure & Engineering',
    securityId: '11483',
    lotSize: 150,
    strikeStep: 50,
    avgVol20DM: 2.10,
    approxLtp: 3560.00,
    isFnO: true,
  },
  {
    ticker: 'AXISBANK',
    name: 'Axis Bank Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Private Banking',
    securityId: '5900',
    lotSize: 625,
    strikeStep: 20,
    avgVol20DM: 7.40,
    approxLtp: 1180.00,
    isFnO: true,
  },
  {
    ticker: 'TATAMOTORS',
    name: 'Tata Motors Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Automobile Manufacturers',
    securityId: '3456',
    lotSize: 550,
    strikeStep: 20,
    avgVol20DM: 8.90,
    approxLtp: 984.40,
    isFnO: true,
  },
  {
    ticker: 'MARUTI',
    name: 'Maruti Suzuki India Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Automobile Manufacturers',
    securityId: '10999',
    lotSize: 50,
    strikeStep: 200,
    avgVol20DM: 0.65,
    approxLtp: 12450.00,
    isFnO: true,
  },
  {
    ticker: 'BAJFINANCE',
    name: 'Bajaj Finance Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Non-Banking Financial Services (NBFC)',
    securityId: '317',
    lotSize: 125,
    strikeStep: 100,
    avgVol20DM: 1.10,
    approxLtp: 7240.00,
    isFnO: true,
  },
  {
    ticker: 'TATASTEEL',
    name: 'Tata Steel Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Iron & Steel / Metals',
    securityId: '3499',
    lotSize: 5500,
    strikeStep: 2.5,
    avgVol20DM: 32.00,
    approxLtp: 154.50,
    isFnO: true,
  },
  {
    ticker: 'ITC',
    name: 'ITC Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'FMCG & Cigarettes / Hotels',
    securityId: '1660',
    lotSize: 1600,
    strikeStep: 10,
    avgVol20DM: 12.00,
    approxLtp: 495.00,
    isFnO: true,
  },
  {
    ticker: 'SUNPHARMA',
    name: 'Sun Pharmaceutical Industries Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Pharmaceuticals',
    securityId: '3351',
    lotSize: 350,
    strikeStep: 20,
    avgVol20DM: 2.80,
    approxLtp: 1860.00,
    isFnO: true,
  },
  {
    ticker: 'WIPRO',
    name: 'Wipro Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Information Technology',
    securityId: '3787',
    lotSize: 1500,
    strikeStep: 10,
    avgVol20DM: 8.50,
    approxLtp: 535.00,
    isFnO: true,
  },
  {
    ticker: 'HINDUNILVR',
    name: 'Hindustan Unilever Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'FMCG & Consumer Goods',
    securityId: '1394',
    lotSize: 300,
    strikeStep: 50,
    avgVol20DM: 1.80,
    approxLtp: 2780.00,
    isFnO: true,
  },
  {
    ticker: 'TITAN',
    name: 'Titan Company Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Gems, Jewellery & Luxury',
    securityId: '3506',
    lotSize: 175,
    strikeStep: 50,
    avgVol20DM: 1.20,
    approxLtp: 3680.00,
    isFnO: true,
  },
  {
    ticker: 'ADANIENT',
    name: 'Adani Enterprises Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Metals, Mining & Trading',
    securityId: '25',
    lotSize: 300,
    strikeStep: 50,
    avgVol20DM: 2.60,
    approxLtp: 3050.00,
    isFnO: true,
  },
  {
    ticker: 'ADANIPORTS',
    name: 'Adani Ports and Special Economic Zone Limited',
    segment: 'NSE_FNO',
    exchange: 'NSE',
    sector: 'Ports & Infrastructure',
    securityId: '15083',
    lotSize: 400,
    strikeStep: 20,
    avgVol20DM: 3.40,
    approxLtp: 1420.00,
    isFnO: true,
  },
  {
    ticker: 'ZOMATO',
    name: 'Zomato Limited (Cash Equity Only)',
    segment: 'NSE_EQ',
    exchange: 'NSE',
    sector: 'Online Food Delivery & Quick Commerce',
    securityId: '5097',
    lotSize: 1,
    strikeStep: 5,
    avgVol20DM: 19.00,
    approxLtp: 264.80,
    isFnO: false,
  },
];

/**
 * Converts a StockMasterItem into a live tracking Stock object
 */
export function convertMasterToStock(master: StockMasterItem): Stock {
  return {
    ticker: master.ticker,
    name: master.name,
    isFnO: master.isFnO,
    segment: master.segment,
    sector: master.sector,
    securityId: master.securityId,
    lotSize: master.lotSize,
    strikeStep: master.strikeStep,
    spotLtp: master.approxLtp || 1000,
    todayVolM: +(master.avgVol20DM * 0.4).toFixed(2),
    avgVol20DM: master.avgVol20DM,
    hasCrossed20D: false,
    crossoverTime: null,
    crossoverSpotPrice: null,
    ivPct: master.isFnO ? 16.5 : 0,
    justCrossedHighlight: false,
  };
}

/**
 * Finds master stock info by ticker
 */
export function getStockMasterByTicker(ticker: string): StockMasterItem | undefined {
  const norm = ticker.trim().toUpperCase();
  return STOCK_MASTER_CATALOG.find((s) => s.ticker === norm);
}
